### ISSUE TITLE
Template deployment via azuredeploy.json fails with several errors

### ISSUE THREAD

**Issue by jesweare** [mspnp/cognitive-services-reference-implementation#14]
The CLI command that runs a custom deployment, using the file `\src\azuredeploy.json`, fails with several errors.

```
az deployment group create \
    -g $RESOURCE_GROUP_NAME \
    --template-file $TEMPLATE_FILE \
    --parameters \
        cognitiveServicesAccountName=$COGNITIVE_SERVICES_ACCOUNT_NAME \
        keyVaultResourceGroupName=$KEY_VAULT_RESOURCE_GROUP_NAME \
        keyVaultName=$KEYVAULT_NAME \
        sitesCognitiveFuncPipelineName=$FUNCTION_APP_NAME \
        sitesTokenApiServiceName=$WEB_APP_NAME \
        existingServicePrincipalAppId=$SP_OBJECT_ID \
        existingServicePrincipalTenantId=$SP_APP_ID \
        existingServicePrincipalAppPassword=$SP_CLIENT_SECRET
```

Namely the `Microsoft.KeyVault/vaults/secrets` and `Microsoft.ManagedIdentity/Identities` operation (in my subscription's case) are failing with NotFound.
Below is a screenshot of the deployment operation details that can be seen in the Azure portal. A screenshot is used here for convenience, as the outputted JSON of the deployment details does not associate the operation type with the operation status.
For reference, the correlation ID is `cf2dbe7a-6433-40b9-a19f-6459fca0bb7e`.

![image](https://user-images.githubusercontent.com/23375232/121618747-52f17280-caa2-11eb-85ba-caec761288ce.png)

When running the `\src\azuredeploy.json` template directly from the Azure Portal, and monitoring the deployment progress, I observed that the `Microsoft.KeyVault/vaults/secrets` operations were running in parallel with other deployment operations. It seems that this behavior is the cause of the error, as the necessary resource to extract keys/secrets are not created when such operations have initiated.

Although the `Microsoft.KeyVault/vaults/secrets` resources defined in `\src\azuredeploy.json` contains a `dependsOn` entry to assume the dependent services already exist, the dependency does not appear to come into effect. This may be related to the behavior described in the blog post below.
https://bmoore-msft.blog/2020/07/26/resource-not-found-dependson-is-not-working/

I believe a review of the `\src\azuredeploy.json` file is necessary to ensure that dependencies among defined resources are consistent in run-time as well.

**Comment by jtjk** [comment]
I have same problem
